# Generated by Django 5.2.5 on 2026-06-08 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='votante',
            name='intentos_fallidos',
            field=models.IntegerField(default=0),
        ),
    ]
