# Generated by Django 5.2.5 on 2026-06-03 04:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntentoAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni_ingresado', models.CharField(max_length=8)),
                ('etapa', models.CharField(choices=[('dni', 'Verificación DNI'), ('foto', 'Foto DNI'), ('rostro', 'Rostro')], max_length=20)),
                ('resultado', models.CharField(choices=[('exitoso', 'Exitoso'), ('fallido', 'Fallido')], max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('detalle', models.TextField(blank=True)),
                ('votante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Intento de Acceso',
                'verbose_name_plural': 'Intentos de Acceso',
            },
        ),
    ]
