# Generated by Django 4.2.30 on 2026-05-24 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voto',
            options={},
        ),
        migrations.AddField(
            model_name='voto',
            name='en_blanco',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='voto',
            name='candidato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='votacion.candidato'),
        ),
    ]
